In [ ]:
!pip install pandas numpy matplotlib seaborn
!pip install nltk spacy regex
!pip install scikit-learn
!pip install transformers
!pip install sentence-transformers
!pip install faiss-cpu
!pip install langchain

Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (2.2.2)
Requirement already satisfied: numpy in /usr/local/lib/python3.12/dist-packages (2.0.2)
Requirement already satisfied: matplotlib in /usr/local/lib/python3.12/dist-packages (3.10.0)
Requirement already satisfied: seaborn in /usr/local/lib/python3.12/dist-packages (0.13.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas) (2025.3)
Requirement already satisfied: contourpy>=1.0.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib) (1.3.3)
Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.12/dist-packages (from matplotlib) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /usr/local/lib/python3.12/dist-packages (from matplotlib) (4.62.1)
Requirement already satisfied: kiwisolver>=1.3.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib) (1.5.0)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.12/dist-packages (from matplotlib) (26.0)
Requirement already satisfied: pillow>=8 in /usr/local/lib/python3.12/dist-packages (from matplotlib) (11.3.0)
Requirement already satisfied: pyparsing>=2.3.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib) (3.3.2)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Requirement already satisfied: nltk in /usr/local/lib/python3.12/dist-packages (3.9.1)
Requirement already satisfied: spacy in /usr/local/lib/python3.12/dist-packages (3.8.11)
Requirement already satisfied: regex in /usr/local/lib/python3.12/dist-packages (2025.11.3)
Requirement already satisfied: click in /usr/local/lib/python3.12/dist-packages (from nltk) (8.3.1)
Requirement already satisfied: joblib in /usr/local/lib/python3.12/dist-packages (from nltk) (1.5.3)
Requirement already satisfied: tqdm in /usr/local/lib/python3.12/dist-packages (from nltk) (4.67.3)
Requirement already satisfied: spacy-legacy<3.1.0,>=3.0.11 in /usr/local/lib/python3.12/dist-packages (from spacy) (3.0.12)
Requirement already satisfied: spacy-loggers<2.0.0,>=1.0.0 in /usr/local/lib/python3.12/dist-packages (from spacy) (1.0.5)
Requirement already satisfied: murmurhash<1.1.0,>=0.28.0 in /usr/local/lib/python3.12/dist-packages (from spacy) (1.0.15)
Requirement already satisfied: cymem<2.1.0,>=2.0.2 in /usr/local/lib/python3.12/dist-packages (from spacy) (2.0.13)
Requirement already satisfied: preshed<3.1.0,>=3.0.2 in /usr/local/lib/python3.12/dist-packages (from spacy) (3.0.12)
Requirement already satisfied: thinc<8.4.0,>=8.3.4 in /usr/local/lib/python3.12/dist-packages (from spacy) (8.3.10)
Requirement already satisfied: wasabi<1.2.0,>=0.9.1 in /usr/local/lib/python3.12/dist-packages (from spacy) (1.1.3)
Requirement already satisfied: srsly<3.0.0,>=2.4.3 in /usr/local/lib/python3.12/dist-packages (from spacy) (2.5.2)
Requirement already satisfied: catalogue<2.1.0,>=2.0.6 in /usr/local/lib/python3.12/dist-packages (from spacy) (2.0.10)
Requirement already satisfied: weasel<0.5.0,>=0.4.2 in /usr/local/lib/python3.12/dist-packages (from spacy) (0.4.3)
Requirement already satisfied: typer-slim<1.0.0,>=0.3.0 in /usr/local/lib/python3.12/dist-packages (from spacy) (0.24.0)
Requirement already satisfied: numpy>=1.19.0 in /usr/local/lib/python3.12/dist-packages (from spacy) (2.0.2)
Requirement already satisfied: requests<3.0.0,>=2.13.0 in /usr/local/lib/python3.12/dist-packages (from spacy) (2.32.4)
Requirement already satisfied: pydantic!=1.8,!=1.8.1,<3.0.0,>=1.7.4 in /usr/local/lib/python3.12/dist-packages (from spacy) (2.12.3)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.12/dist-packages (from spacy) (3.1.6)
Requirement already satisfied: setuptools in /usr/local/lib/python3.12/dist-packages (from spacy) (75.2.0)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.12/dist-packages (from spacy) (26.0)
Requirement already satisfied: annotated-types>=0.6.0 in /usr/local/lib/python3.12/dist-packages (from pydantic!=1.8,!=1.8.1,<3.0.0,>=1.7.4->spacy) (0.7.0)
Requirement already satisfied: pydantic-core==2.41.4 in /usr/local/lib/python3.12/dist-packages (from pydantic!=1.8,!=1.8.1,<3.0.0,>=1.7.4->spacy) (2.41.4)
Requirement already satisfied: typing-extensions>=4.14.1 in /usr/local/lib/python3.12/dist-packages (from pydantic!=1.8,!=1.8.1,<3.0.0,>=1.7.4->spacy) (4.15.0)
Requirement already satisfied: typing-inspection>=0.4.2 in /usr/local/lib/python3.12/dist-packages (from pydantic!=1.8,!=1.8.1,<3.0.0,>=1.7.4->spacy) (0.4.2)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests<3.0.0,>=2.13.0->spacy) (3.4.6)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests<3.0.0,>=2.13.0->spacy) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests<3.0.0,>=2.13.0->spacy) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests<3.0.0,>=2.13.0->spacy) (2026.2.25)
Requirement already satisfied: blis<1.4.0,>=1.3.0 in /usr/local/lib/python3.12/dist-packages (from thinc<8.4.0,>=8.3.4->spacy) (1.3.3)
Requirement already satisfied: confection<1.0.0,>=0.0.1 in /usr/local/lib/python3.12/dist-packages (from thinc<8.4.0,>=8.3.4->spacy) (0.1.5)
Requirement already satisfied: typer>=0.24.0 in /usr/local/lib/python3.12/dist-packages (from typer-slim<1.0.0,>=0.3.0->spacy) (0.24.1)
Requirement already satisfied: cloudpathlib<1.0.0,>=0.7.0 in /usr/local/lib/python3.12/dist-packages (from weasel<0.5.0,>=0.4.2->spacy) (0.23.0)
Requirement already satisfied: smart-open<8.0.0,>=5.2.1 in /usr/local/lib/python3.12/dist-packages (from weasel<0.5.0,>=0.4.2->spacy) (7.5.1)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.12/dist-packages (from jinja2->spacy) (3.0.3)
Requirement already satisfied: wrapt in /usr/local/lib/python3.12/dist-packages (from smart-open<8.0.0,>=5.2.1->weasel<0.5.0,>=0.4.2->spacy) (2.1.2)
Requirement already satisfied: shellingham>=1.3.0 in /usr/local/lib/python3.12/dist-packages (from typer>=0.24.0->typer-slim<1.0.0,>=0.3.0->spacy) (1.5.4)
Requirement already satisfied: rich>=12.3.0 in /usr/local/lib/python3.12/dist-packages (from typer>=0.24.0->typer-slim<1.0.0,>=0.3.0->spacy) (13.9.4)
Requirement already satisfied: annotated-doc>=0.0.2 in /usr/local/lib/python3.12/dist-packages (from typer>=0.24.0->typer-slim<1.0.0,>=0.3.0->spacy) (0.0.4)
Requirement already satisfied: markdown-it-py>=2.2.0 in /usr/local/lib/python3.12/dist-packages (from rich>=12.3.0->typer>=0.24.0->typer-slim<1.0.0,>=0.3.0->spacy) (4.0.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /usr/local/lib/python3.12/dist-packages (from rich>=12.3.0->typer>=0.24.0->typer-slim<1.0.0,>=0.3.0->spacy) (2.19.2)
Requirement already satisfied: mdurl~=0.1 in /usr/local/lib/python3.12/dist-packages (from markdown-it-py>=2.2.0->rich>=12.3.0->typer>=0.24.0->typer-slim<1.0.0,>=0.3.0->spacy) (0.1.2)
Requirement already satisfied: scikit-learn in /usr/local/lib/python3.12/dist-packages (1.6.1)
Requirement already satisfied: numpy>=1.19.5 in /usr/local/lib/python3.12/dist-packages (from scikit-learn) (2.0.2)
Requirement already satisfied: scipy>=1.6.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn) (1.16.3)
Requirement already satisfied: joblib>=1.2.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn) (1.5.3)
Requirement already satisfied: threadpoolctl>=3.1.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn) (3.6.0)
Requirement already satisfied: transformers in /usr/local/lib/python3.12/dist-packages (5.0.0)
Requirement already satisfied: filelock in /usr/local/lib/python3.12/dist-packages (from transformers) (3.25.2)
Requirement already satisfied: huggingface-hub<2.0,>=1.3.0 in /usr/local/lib/python3.12/dist-packages (from transformers) (1.7.1)
Requirement already satisfied: numpy>=1.17 in /usr/local/lib/python3.12/dist-packages (from transformers) (2.0.2)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.12/dist-packages (from transformers) (26.0)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.12/dist-packages (from transformers) (6.0.3)
Requirement already satisfied: regex!=2019.12.17 in /usr/local/lib/python3.12/dist-packages (from transformers) (2025.11.3)
Requirement already satisfied: tokenizers<=0.23.0,>=0.22.0 in /usr/local/lib/python3.12/dist-packages (from transformers) (0.22.2)
Requirement already satisfied: typer-slim in /usr/local/lib/python3.12/dist-packages (from transformers) (0.24.0)
Requirement already satisfied: safetensors>=0.4.3 in /usr/local/lib/python3.12/dist-packages (from transformers) (0.7.0)
Requirement already satisfied: tqdm>=4.27 in /usr/local/lib/python3.12/dist-packages (from transformers) (4.67.3)
Requirement already satisfied: fsspec>=2023.5.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<2.0,>=1.3.0->transformers) (2025.3.0)
Requirement already satisfied: hf-xet<2.0.0,>=1.4.2 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<2.0,>=1.3.0->transformers) (1.4.2)
Requirement already satisfied: httpx<1,>=0.23.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<2.0,>=1.3.0->transformers) (0.28.1)
Requirement already satisfied: typer in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<2.0,>=1.3.0->transformers) (0.24.1)
Requirement already satisfied: typing-extensions>=4.1.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<2.0,>=1.3.0->transformers) (4.15.0)
Requirement already satisfied: anyio in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.3.0->transformers) (4.12.1)
Requirement already satisfied: certifi in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.3.0->transformers) (2026.2.25)
Requirement already satisfied: httpcore==1.* in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.3.0->transformers) (1.0.9)
Requirement already satisfied: idna in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.3.0->transformers) (3.11)
Requirement already satisfied: h11>=0.16 in /usr/local/lib/python3.12/dist-packages (from httpcore==1.*->httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.3.0->transformers) (0.16.0)
Requirement already satisfied: click>=8.2.1 in /usr/local/lib/python3.12/dist-packages (from typer->huggingface-hub<2.0,>=1.3.0->transformers) (8.3.1)
Requirement already satisfied: shellingham>=1.3.0 in /usr/local/lib/python3.12/dist-packages (from typer->huggingface-hub<2.0,>=1.3.0->transformers) (1.5.4)
Requirement already satisfied: rich>=12.3.0 in /usr/local/lib/python3.12/dist-packages (from typer->huggingface-hub<2.0,>=1.3.0->transformers) (13.9.4)
Requirement already satisfied: annotated-doc>=0.0.2 in /usr/local/lib/python3.12/dist-packages (from typer->huggingface-hub<2.0,>=1.3.0->transformers) (0.0.4)
Requirement already satisfied: markdown-it-py>=2.2.0 in /usr/local/lib/python3.12/dist-packages (from rich>=12.3.0->typer->huggingface-hub<2.0,>=1.3.0->transformers) (4.0.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /usr/local/lib/python3.12/dist-packages (from rich>=12.3.0->typer->huggingface-hub<2.0,>=1.3.0->transformers) (2.19.2)
Requirement already satisfied: mdurl~=0.1 in /usr/local/lib/python3.12/dist-packages (from markdown-it-py>=2.2.0->rich>=12.3.0->typer->huggingface-hub<2.0,>=1.3.0->transformers) (0.1.2)
Requirement already satisfied: sentence-transformers in /usr/local/lib/python3.12/dist-packages (5.3.0)
Requirement already satisfied: transformers<6.0.0,>=4.41.0 in /usr/local/lib/python3.12/dist-packages (from sentence-transformers) (5.0.0)
Requirement already satisfied: huggingface-hub>=0.20.0 in /usr/local/lib/python3.12/dist-packages (from sentence-transformers) (1.7.1)
Requirement already satisfied: torch>=1.11.0 in /usr/local/lib/python3.12/dist-packages (from sentence-transformers) (2.10.0+cu128)
Requirement already satisfied: numpy in /usr/local/lib/python3.12/dist-packages (from sentence-transformers) (2.0.2)
Requirement already satisfied: scikit-learn in /usr/local/lib/python3.12/dist-packages (from sentence-transformers) (1.6.1)
Requirement already satisfied: scipy in /usr/local/lib/python3.12/dist-packages (from sentence-transformers) (1.16.3)
Requirement already satisfied: typing_extensions>=4.5.0 in /usr/local/lib/python3.12/dist-packages (from sentence-transformers) (4.15.0)
Requirement already satisfied: tqdm in /usr/local/lib/python3.12/dist-packages (from sentence-transformers) (4.67.3)
Requirement already satisfied: filelock>=3.10.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.20.0->sentence-transformers) (3.25.2)
Requirement already satisfied: fsspec>=2023.5.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.20.0->sentence-transformers) (2025.3.0)
Requirement already satisfied: hf-xet<2.0.0,>=1.4.2 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.20.0->sentence-transformers) (1.4.2)
Requirement already satisfied: httpx<1,>=0.23.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.20.0->sentence-transformers) (0.28.1)
Requirement already satisfied: packaging>=20.9 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.20.0->sentence-transformers) (26.0)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.20.0->sentence-transformers) (6.0.3)
Requirement already satisfied: typer in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.20.0->sentence-transformers) (0.24.1)
Requirement already satisfied: setuptools in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers) (75.2.0)
Requirement already satisfied: sympy>=1.13.3 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers) (1.14.0)
Requirement already satisfied: networkx>=2.5.1 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers) (3.6.1)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers) (3.1.6)
Requirement already satisfied: cuda-bindings==12.9.4 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers) (12.9.4)
Requirement already satisfied: nvidia-cuda-nvrtc-cu12==12.8.93 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers) (12.8.93)
Requirement already satisfied: nvidia-cuda-runtime-cu12==12.8.90 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers) (12.8.90)
Requirement already satisfied: nvidia-cuda-cupti-cu12==12.8.90 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers) (12.8.90)
Requirement already satisfied: nvidia-cudnn-cu12==9.10.2.21 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers) (9.10.2.21)
Requirement already satisfied: nvidia-cublas-cu12==12.8.4.1 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers) (12.8.4.1)
Requirement already satisfied: nvidia-cufft-cu12==11.3.3.83 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers) (11.3.3.83)
Requirement already satisfied: nvidia-curand-cu12==10.3.9.90 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers) (10.3.9.90)
Requirement already satisfied: nvidia-cusolver-cu12==11.7.3.90 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers) (11.7.3.90)
Requirement already satisfied: nvidia-cusparse-cu12==12.5.8.93 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers) (12.5.8.93)
Requirement already satisfied: nvidia-cusparselt-cu12==0.7.1 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers) (0.7.1)
Requirement already satisfied: nvidia-nccl-cu12==2.27.5 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers) (2.27.5)
Requirement already satisfied: nvidia-nvshmem-cu12==3.4.5 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers) (3.4.5)
Requirement already satisfied: nvidia-nvtx-cu12==12.8.90 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers) (12.8.90)
Requirement already satisfied: nvidia-nvjitlink-cu12==12.8.93 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers) (12.8.93)
Requirement already satisfied: nvidia-cufile-cu12==1.13.1.3 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers) (1.13.1.3)
Requirement already satisfied: triton==3.6.0 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers) (3.6.0)
Requirement already satisfied: cuda-pathfinder~=1.1 in /usr/local/lib/python3.12/dist-packages (from cuda-bindings==12.9.4->torch>=1.11.0->sentence-transformers) (1.4.3)
Requirement already satisfied: regex!=2019.12.17 in /usr/local/lib/python3.12/dist-packages (from transformers<6.0.0,>=4.41.0->sentence-transformers) (2025.11.3)
Requirement already satisfied: tokenizers<=0.23.0,>=0.22.0 in /usr/local/lib/python3.12/dist-packages (from transformers<6.0.0,>=4.41.0->sentence-transformers) (0.22.2)
Requirement already satisfied: typer-slim in /usr/local/lib/python3.12/dist-packages (from transformers<6.0.0,>=4.41.0->sentence-transformers) (0.24.0)
Requirement already satisfied: safetensors>=0.4.3 in /usr/local/lib/python3.12/dist-packages (from transformers<6.0.0,>=4.41.0->sentence-transformers) (0.7.0)
Requirement already satisfied: joblib>=1.2.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn->sentence-transformers) (1.5.3)
Requirement already satisfied: threadpoolctl>=3.1.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn->sentence-transformers) (3.6.0)
Requirement already satisfied: anyio in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface-hub>=0.20.0->sentence-transformers) (4.12.1)
Requirement already satisfied: certifi in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface-hub>=0.20.0->sentence-transformers) (2026.2.25)
Requirement already satisfied: httpcore==1.* in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface-hub>=0.20.0->sentence-transformers) (1.0.9)
Requirement already satisfied: idna in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface-hub>=0.20.0->sentence-transformers) (3.11)
Requirement already satisfied: h11>=0.16 in /usr/local/lib/python3.12/dist-packages (from httpcore==1.*->httpx<1,>=0.23.0->huggingface-hub>=0.20.0->sentence-transformers) (0.16.0)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /usr/local/lib/python3.12/dist-packages (from sympy>=1.13.3->torch>=1.11.0->sentence-transformers) (1.3.0)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.12/dist-packages (from jinja2->torch>=1.11.0->sentence-transformers) (3.0.3)
Requirement already satisfied: click>=8.2.1 in /usr/local/lib/python3.12/dist-packages (from typer->huggingface-hub>=0.20.0->sentence-transformers) (8.3.1)
Requirement already satisfied: shellingham>=1.3.0 in /usr/local/lib/python3.12/dist-packages (from typer->huggingface-hub>=0.20.0->sentence-transformers) (1.5.4)

In [4]:
import pandas as pd
import re

In [6]:
data=pd.read_csv("/content/final_dataset.csv")
data.head()

,product_name,review,rating
0,Apple MacBook AIR Apple M2 - (8 GB/256 GB SSD/...,"Loved it, it's my first MacBook that I earned ...",5
1,Apple MacBook AIR Apple M2 - (8 GB/256 GB SSD/...,Battery lasted longer than my first relationsh...,5
2,Apple MacBook AIR Apple M2 - (8 GB/256 GB SSD/...,Such a great deal.. very happy with the perfor...,5
3,Apple MacBook AIR Apple M2 - (8 GB/256 GB SSD/...,"Awesome build quality and very good display, b...",4
4,Apple MacBook AIR Apple M2 - (8 GB/256 GB SSD/...,When i ordered and came to know about seller r...,5

In [ ]:
import re

def clean_text(text):
    text = str(text)
    text = text.lower()
    text = re.sub(r"http\S+", "", text)
    text = re.sub(r"@\w+", "", text)  # remove mentions
    text = re.sub(r"#\w+", "", text)  # remove hashtags
    text = re.sub(r"[^a-zA-Z\s]", "", text)
    text = re.sub(r"\s+", " ", text).strip()
    return text

data['clean_review'] = data['review'].apply(clean_text)

In [ ]:
import re

tanglish_map = {
    "romba": "very",
    "nalla": "good",
    "mosam": "bad",
    "super": "excellent",
    "waste": "poor",
    "iruku": "is",
    "vandhuchu": "arrived",
    "varudhu": "is coming",
    "aagudhu": "become",
    "illa":"not",
    "illai": "not",
    "konjam": "little",
    "adhigam": "more",
    "nadakudhu": "working",
    "decent": "average",
    "kammi": "less",
    "mudiyadhu": "cannot",
    "panna": "do",
    "pidichiruku": "liked",
    "nala": "good",
    "kudukudhu": "giving",
    "upchanam":"disappointment",
    "kadupu":"irritation",
    "jolly ":"happy",
    "kastam":"difficult",
    "mokka":"bad",
    "semma":"awesome",
    "jaasthi":"too much",
    "vera level":"excellent",
    "pakka":"defienitely",
    "azhagana":"beautiful",
    "mass":"cool",
    "mudiyala":"couldn't do it",
    "theriyudhu":"feels like",
    "theriyadhu":"doesn't seem",
    "pannudhu":"it does",
    "pannrom":"we are doing",
    "sollanum":"should say",
    "paakanum":"should see",
    "kadaisila":"at last",
    "muzhusa":"completely",
    "sandai":"issue",
    "tension illai":"no worries"



}

remove_words = {"la", "ah", "ku", "than","machan","bro","nanbaa","anna","ayyo","adei"}

def normalize_tanglish(text):
    words = text.split()
    normalized_words = []

    for word in words:
        if word in remove_words:
            continue
        normalized_word = tanglish_map.get(word, word)
        normalized_words.append(normalized_word)

    return " ".join(normalized_words)

data['normalized_review'] = data['clean_review'].apply(normalize_tanglish)

In [ ]:
data

,product_name,review,rating,clean_review,normalized_review
0,Apple MacBook AIR Apple M2 - (8 GB/256 GB SSD/...,"Loved it, it's my first MacBook that I earned ...",5,loved it its my first macbook that i earned fr...,loved it its my first macbook that i earned fr...
1,Apple MacBook AIR Apple M2 - (8 GB/256 GB SSD/...,Battery lasted longer than my first relationsh...,5,battery lasted longer than my first relationsh...,battery lasted longer my first relationship da...
2,Apple MacBook AIR Apple M2 - (8 GB/256 GB SSD/...,Such a great deal.. very happy with the perfor...,5,such a great deal very happy with the performa...,such a great deal very happy with the performa...
3,Apple MacBook AIR Apple M2 - (8 GB/256 GB SSD/...,"Awesome build quality and very good display, b...",4,awesome build quality and very good display ba...,awesome build quality and very good display ba...
4,Apple MacBook AIR Apple M2 - (8 GB/256 GB SSD/...,When i ordered and came to know about seller r...,5,when i ordered and came to know about seller r...,when i ordered and came to know about seller r...
...,...,...,...,...,...
25302,Samsung Galaxy Book4,Touch response quick ah iruku finger swipe acc...,5,touch response quick ah iruku finger swipe acc...,touch response quick is finger swipe accurate ...
25303,Samsung Galaxy Book4,Keyboard keys stiff iruku typing panna romba k...,2,keyboard keys stiff iruku typing panna romba k...,keyboard keys stiff is typing do very difficul...
25304,ASUS Vivobook Go 14,Gorilla glass display scratch vechi kuda romba...,5,gorilla glass display scratch vechi kuda romba...,gorilla glass display scratch vechi kuda very ...
25305,Lenovo Chromebook,Speaker mono iruku stereo irundha better,3,speaker mono iruku stereo irundha better,speaker mono is stereo irundha better
25306,ASUS Vivobook Go 14,USB transfer speed romba fast data edukka wait...,5,usb transfer speed romba fast data edukka wait...,usb transfer speed very fast data edukka waiti...

In [ ]:
from difflib import get_close_matches

# 3️⃣ Remove repeated characters
def remove_repeats(text):
    return re.sub(r'(.)\1{2,}', r'\1\1', text)
data['no_repeat_review'] = data['normalized_review'].apply(remove_repeats)

# 4️⃣ Controlled spelling correction
english_vocab = ["battery","camera","quality","price","delivery",
                 "excellent","poor","slow","good","bad","average",
                 "fast","cheap","expensive","very","laptop","bluetooth",
                 "android","flipkart","awesome","thank","excellent",
                 "product","beautiful","amazing","love","average",
                 "super","usefull","beast","wow","terrific","heat",
                 "performance","satisfy","superb","motherboard"
                 ]

def correct_word(word):
    matches = get_close_matches(word, english_vocab, n=1, cutoff=0.8)
    return matches[0] if matches else word

def correct_spelling(text):
    return " ".join([correct_word(w) for w in text.split()])

data['final_review'] = data['no_repeat_review'].apply(correct_spelling)

In [ ]:
aspects = {

    "battery": [
        "battery", "charge", "charging", "charger", "drain",
        "backup", "power", "mah", "full charge",
        "battery life", "battery backup",
        "drain fast", "charging speed",
        "slow charge", "fast charge"
    ],

    "price": [
        "price", "cost", "expensive", "cheap", "affordable",
        "worth", "overpriced", "budget", "money",
        "value", "value for money",
        "high price", "low price","best cost","discount","rate",
        "buy"

    ],

    "quality": [
        "quality", "durable", "poor", "excellent",
        "premium", "build quality", "material",
        "strong", "weak", "solid",
        "finish", "performance quality","experience","laptop",
        "phone","mobile","best cost","problem","worst",
        "earbud","masterpiece","panel","keyboard",
        "product","watch","machine","refrigerator","samsung",
        "freezer"," fridge","tv","macbook","apple","android",
        "average product","hp","asus","mac","storage"


    ],
    "delivery": [
        "delivery", "shipping", "courier", "late",
        "delay", "fast delivery", "on time",
        "arrived", "arrival", "delivered",
        "packing delay"
    ],

    "camera": [
        "camera", "photo", "video", "picture",
        "selfie", "portrait", "night mode",
        "zoom", "lens", "clarity",
        "front camera", "rear camera"
    ],

    "packaging": [
        "packaging", "box", "damage", "broken",
        "seal", "wrap", "packed",
        "outer box", "inside box",
        "damaged box", "good packaging","package"
    ],

    "performance": [
        "performance", "speed", "fast", "slow",
        "lag", "hang", "smooth", "processor",
        "ram", "gaming", "multitasking",
        "heating", "heat issue","work","bluetooth","sync",
        "slot","network","vibration","tracking",
        "mind blowing" ,"graphics","windows","ms office",
        "running time","lock","software","usb","wifi","heat",
        "memory"

    ],

    "display": [
        "display", "screen", "brightness",
        "resolution", "touch", "touchscreen",
        "refresh rate", "color", "visual",
        "clarity", "screen size","hd","backlight"

    ],

    "sound": [
        "sound", "audio", "speaker", "volume",
        "bass", "noise", "mic",
        "call quality", "voice clarity"
    ],

    "design": [
        "design", "look", "style",
        "weight", "size", "slim",
        "color", "appearance", "build","strap",
        "motherboard"
    ],
    "generic": [
        "superb","awesome","great",
        "bad","good","nice","best","perfect",
        "thank","happy","for","beautiful",
        "amazing","genuine","very well","ok",
        "satisfied","better","fantastic","love it",
        "delightful","marvellous","like","fabulous",
        "overall","fine","love","average",
        "brilliant","terrific","super","wonderful",
        "beast","valuable","osm","wow","gud","gorgeous",
        "must","useful","normal","cool","outstanding",
        "disappointed","all is well","terrible","satisfactory"
    ]

}

In [ ]:
def extract_aspects(text):
    found = []
    for aspect, words in aspects.items():
        if any(word in text for word in words):
            found.append(aspect)
    return found

data['aspects'] = data['final_review'].apply(extract_aspects)

In [ ]:
brand_list = [
    "HP", "Dell", "Lenovo", "Asus", "Acer",
    "Apple", "MSI", "Samsung", "LG","Infinix",
    "ZEBRONICS","realme","Primebook","CHUWI",
    "Ultimus","AXL","Colorful","walker"
]
def extract_brand(product_name):
    for brand in brand_list:
        if brand.lower() in product_name.lower():
            return brand
    return "Other brands"

data['brand'] = data['product_name'].apply(extract_brand)

In [ ]:
from transformers import pipeline

In [ ]:
sentiment_model = pipeline(
    "sentiment-analysis",
    model="nlptown/bert-base-multilingual-uncased-sentiment"
)

/usr/local/lib/python3.12/dist-packages/huggingface_hub/utils/_auth.py:94: UserWarning:
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(

config.json:   0%|          | 0.00/953 [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/669M [00:00<?, ?B/s]

Loading weights:   0%|          | 0/201 [00:00<?, ?it/s]

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
WARNING:huggingface_hub.utils._http:Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

tokenizer_config.json:   0%|          | 0.00/39.0 [00:00<?, ?B/s]

vocab.txt: 0.00B [00:00, ?B/s]

special_tokens_map.json:   0%|          | 0.00/112 [00:00<?, ?B/s]

In [ ]:
reviews = data['final_review'].astype(str).tolist()

In [ ]:

results = sentiment_model(reviews, batch_size=64)

In [ ]:
 data['sentiment_output'] = [result['label'] for result in results]

In [ ]:
data['sentiment_output']

0        5 stars
1        3 stars
2        5 stars
3        5 stars
4        5 stars
          ...
25302    5 stars
25303    3 stars
25304    5 stars
25305    3 stars
25306    2 stars
Name: sentiment_output, Length: 25307, dtype: object

In [ ]:
from sklearn.model_selection import train_test_split

In [ ]:
X = data['final_review']
y = data['sentiment_output']

In [ ]:
X_train,X_test,y_train,y_test=train_test_split(X,y,train_size=0.2,random_state=42,stratify=y)

In [ ]:
from sklearn.feature_extraction.text import TfidfVectorizer

tfidf = TfidfVectorizer( max_features=5000, ngram_range=(1,2) )

X_train_tfidf = tfidf.fit_transform(X_train)
X_test_tfidf = tfidf.transform(X_test)

In [ ]:
from sklearn.linear_model import LogisticRegression

model = LogisticRegression(max_iter=1000)

model.fit(X_train_tfidf, y_train)

LogisticRegression(max_iter=1000)

In [ ]:
y_pred = model.predict(X_test_tfidf)

In [ ]:
from sklearn.metrics import classification_report, accuracy_score, confusion_matrix

print("Accuracy:", accuracy_score(y_test, y_pred))

Accuracy: 0.7978860021732688

In [ ]:
def convert_to_sentiment(label):
    stars = int(label[0])

    if stars >= 4:
        return "Positive"
    elif stars == 3:
        return "Neutral"
    else:
        return "Negative"

In [ ]:
data['sentiment'] = data['sentiment_output'].apply(convert_to_sentiment)

In [ ]:
data_exploded= data.explode('aspects')

In [ ]:
aspect_sentiment = (
    data_exploded
    .groupby(['aspects', 'sentiment'])
    .size()
    .unstack(fill_value=0)
)

In [ ]:
aspect_sentiment['positive_percent'] = (
    aspect_sentiment['Positive'] /
    aspect_sentiment.sum(axis=1)
) * 100

In [ ]:
aspect_sentiment['positive_percent']

aspects
battery        54.543779
camera         52.592593
delivery       62.447257
design         69.473987
display        56.451250
generic        75.116206
packaging      63.440860
performance    61.994057
price          72.492983
quality        71.064844
sound          48.277584
Name: positive_percent, dtype: float64

In [ ]:
brand_aspect = (
    data_exploded
    .groupby(['brand','aspects','sentiment'])
    .size()
    .unstack(fill_value=0)
)

In [ ]:
brand_aspect['positive_percent'] = (
    brand_aspect['Positive'] /
    brand_aspect.sum(axis=1)
) * 100

In [ ]:
brand_aspect['positive_percent']

brand   aspects
AXL     battery          0.000000
        camera         100.000000
        design          75.000000
        display         66.666667
        generic         66.666667
                          ...
walker  generic         70.114943
        performance     36.363636
        price           68.888889
        quality         62.121212
        sound           25.000000
Name: positive_percent, Length: 193, dtype: float64

In [ ]:
comparison_table = brand_aspect.reset_index().pivot(
    index='brand',
    columns='aspects',
    values='positive_percent'
)

In [ ]:
comparison_table

aspects,battery,camera,delivery,design,display,generic,packaging,performance,price,quality,sound
brand,,,,,,,,,,,
AXL,0.000000,100.000000,NaN,75.000000,66.666667,66.666667,NaN,42.857143,92.857143,73.684211,0.000000
Acer,51.242236,41.353383,50.961538,65.517241,49.480969,73.074347,59.615385,58.313998,70.563140,64.974619,42.268041
Apple,94.011976,88.888889,77.272727,96.212121,91.379310,92.051756,80.769231,88.549618,88.439306,90.867580,81.132075
Asus,57.789855,61.676647,54.621849,69.162996,58.404803,75.143869,66.250000,62.908163,70.948012,71.484729,53.723404
CHUWI,48.760331,19.512195,40.000000,81.818182,74.683544,74.858223,83.333333,54.545455,67.965368,65.393795,71.428571
Colorful,50.000000,88.888889,100.000000,75.862069,72.916667,66.917293,0.000000,73.170732,65.277778,75.728155,69.230769
Dell,30.973451,37.209302,74.074074,56.521739,47.019868,70.000000,69.565217,47.806005,65.328467,64.819945,41.428571
HP,48.387097,50.738916,64.893617,65.625000,51.056730,76.562775,60.563380,61.091073,73.043478,73.056197,43.165468
Infinix,61.212121,59.090909,56.666667,74.637681,51.748252,77.650430,61.538462,61.946903,73.006135,72.743682,42.857143
Lenovo,50.985915,52.631579,58.024691,65.248227,46.781790,71.366906,51.162791,60.147905,69.422311,67.351129,38.521401
MSI,62.722853,60.256410,73.239437,71.542553,67.880795,76.427704,61.538462,68.252327,79.785605,71.976647,47.094801
Other brands,43.478261,0.000000,57.142857,60.000000,61.538462,55.333333,60.000000,37.037037,57.142857,60.563380,63.636364
Primebook,85.714286,62.500000,100.000000,100.000000,87.500000,93.684211,NaN,92.727273,95.833333,93.793103,62.500000
Samsung,67.307692,39.393939,61.111111,71.428571,69.938650,76.862124,44.444444,67.751479,76.892430,80.278884,65.217391
Ultimus,42.105263,42.857143,100.000000,64.705882,50.000000,70.056497,100.000000,56.666667,60.759494,67.441860,0.000000
ZEBRONICS,46.428571,66.666667,100.000000,77.777778,75.000000,73.170732,100.000000,57.142857,75.000000,66.129032,63.636364
realme,95.652174,100.000000,100.000000,92.500000,91.428571,95.918367,100.000000,93.617021,94.871795,94.594595,92.857143
walker,54.545455,0.000000,NaN,60.000000,83.333333,70.114943,NaN,36.363636,68.888889,62.121212,25.000000

In [ ]:
data['rag_text'] = (
    "Brand: " + data['brand'] +
    ", Review: " + data['final_review'] +
    ", Sentiment: " + data['sentiment']
)

In [ ]:
from sentence_transformers import SentenceTransformer

embedding_model = SentenceTransformer('all-MiniLM-L6-v2')

data['embedding'] = data['rag_text'].apply(lambda x: embedding_model.encode(x))

Loading weights:   0%|          | 0/103 [00:00<?, ?it/s]

BertModel LOAD REPORT from: sentence-transformers/all-MiniLM-L6-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

In [ ]:
import faiss
import numpy as np

embeddings = np.vstack(data['embedding'].values)

dimension = embeddings.shape[1]
index = faiss.IndexFlatL2(dimension)
index.add(embeddings)

In [ ]:
def retrieve_reviews_text(query, k=5):
    query_vector = embedding_model.encode([query])
    distances, indices = index.search(query_vector, k)
    return data.iloc[indices[0]]

In [ ]:
context = retrieve_reviews_text("Best price laptop?")

prompt = f"""
Based on the following reviews:
{context['rag_text'].to_string()}

Answer: Which brand has best battery?
"""

In [ ]:
import google.generativeai as genai

genai.configure(api_key="AIzaSyCrHXUtJWEUKqIZuPplcBwhnCP9D-4KUZg")

model = genai.GenerativeModel("models/gemini-2.5-flash")

/usr/local/lib/python3.12/dist-packages/google/colab/_import_hooks/_hook_injector.py:55: FutureWarning:

All support for the `google.generativeai` package has ended. It will no longer be receiving
updates or bug fixes. Please switch to the `google.genai` package as soon as possible.
See README for more details:

https://github.com/google-gemini/deprecated-generative-ai-python/blob/main/README.md

  loader.exec_module(module)

In [ ]:

response = model.generate_content("Test connection")
print(response.text)

Connection successful! I received your message and am able to respond.

How can I assist you?

In [ ]:
def generate_business_insights(query):

    reviews = retrieve_reviews_text(query)
    context = "\n".join(reviews['rag_text'])

    prompt = f"""
    Analyze the following reviews and provide a concise business insight summary:

    {context}
    """

    response = model.generate_content(
        prompt,
        generation_config={
            "max_output_tokens": 748,   # 🔥 LIMIT OUTPUT LENGTH
            "temperature": 0.3
        }
    )

    return response.text.strip().replace("\n", " ")

In [ ]:
generate_business_insights("what about dell performance")

"Dell's product is highly regarded for its solid performance in day-to-day tasks, light gaming, and basic creative work."

In [3]:
import pandas as pd

# Load CSV files
df1 = pd.read_csv("/content/laptops_dataset_final_600.csv")
df2 = pd.read_csv("/content/tanglish_reviews.csv")

# Merge (append rows)
merged = pd.concat([df1, df2], ignore_index=True)

# Save output
merged.to_csv("final_dataset.csv", index=False)

print("Files merged successfully!")

Files merged successfully!